### ISSUE TITLE
Error when trying to run Conpot

### ISSUE THREAD

**Issue by AsherNoor** [d4emonsAVI/conpot#1]
Followed the [host installation steps](https://conpot.readthedocs.io/en/latest/installation/install.html).
When tried to run it, by simply typing "conpot", it throws this error.

`/home/adhd/conpot/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py:29: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "/home/adhd/conpot/bin/conpot", line 45, in <module>
    from conpot.protocols.IEC104.IEC104_server import IEC104Server
  File "/home/adhd/conpot/lib/python3.6/site-packages/conpot/protocols/IEC104/IEC104_server.py", line 17, in <module>
    from conpot.protocols.IEC104.DeviceDataController import DeviceDataController
  File "/home/adhd/conpot/lib/python3.6/site-packages/conpot/protocols/IEC104/DeviceDataController.py", line 19, in <module>
    from conpot.protocols.IEC104.frames import *
  File "/home/adhd/conpot/lib/python3.6/site-packages/conpot/protocols/IEC104/frames.py", line 258, in <module>
    class QOS(Packet):
  File "/home/adhd/conpot/lib/python3.6/site-packages/scapy/base_classes.py", line 345, in __new__
    for f in dct["fields_desc"]
  File "/home/adhd/conpot/lib/python3.6/site-packages/scapy/base_classes.py", line 345, in <listcomp>
    for f in dct["fields_desc"]
  File "/usr/lib/python3.6/inspect.py", line 2488, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))ValueError: 'S/E' is not a valid parameter name`

Screenshot:

![Running-Conpot-Error_Jun1-2023](https://github.com/d4emonsAVI/conpot/assets/60714000/f041d9c8-0165-44d8-9a36-1b79bd4a707f)

**Comment by KorpoleRithika0x1** [comment]
did you build it first?

**Comment by GryphonInfoSec** [comment]
It looks like the '/' (forward slash) is not allowed by the inspect module.

Here is the section of code from Scapy:
/home/adhd/conpot/lib/python3.6/site-packages/scapy/base_classes.py
 # Build and inject signature
        try:
            # Py3 only
            import inspect
            dct["__signature__"] = inspect.Signature([
                inspect.Parameter("_pkt", inspect.Parameter.POSITIONAL_ONLY),
            ] + [
                inspect.Parameter(f.name,
                                  inspect.Parameter.KEYWORD_ONLY,
                                  default=f.default)
                for f in dct["fields_desc"]
            ])
        except (ImportError, AttributeError, KeyError):
            pass
        newcls = cast('Type[scapy.packet.Packet]',
                      type.__new__(cls, name, bases, dct))


Which relies on Inspect to verify formatting:
https://docs.python.org/3.6/library/inspect.html
 name -    The name of the parameter as a string. The name must be a valid Python identifier.
Identifier names in Python can contain numbers (0-9), uppercase letters (A-Z), lowercase letters (a-z), and underscore (_)



The 'S/E' is only found on line 256 of the conpot frames.py file from the traceback:
/home/adhd/conpot/lib/python3.6/site-packages/conpot/protocols/IEC104/frames.py
Line 256        XBitField("S/E", 0, 1), XBitField("QL", 0, 7)]



Once the '/' is removed that should solve this error.

**Comment by AsherNoor** [comment]
**The Solution**
It was a Layer 8 issue, I need to run a build command first:
`python steup.py build`

Then the following commands:
```
cd bin
conpot -f
```

That got it working.

**Comment by GryphonInfoSec** [comment]
> did you build it first?

You don't have to build it when using the pip install.  If you do that means that the package is broken.
