### ISSUE TITLE
Error running conpot from source "No module named 'gevent'"

### ISSUE THREAD

**Issue by GryphonInfoSec** [d4emonsAVI/conpot#4]
Error:
(conpot) adhd@DESKTOP-I1T2G01:~/conpot$ conpot
Traceback (most recent call last):
  File "/home/adhd/conpot/bin/conpot", line 19, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'

**To Reproduce**
Install from directions, until:
#Install the table version of Conpot from PyPI:
Instead install from source, ie. git clone repo
#run conpot 
$ conpot 

**Expected behavior**
This should start the program

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18

**Comment by KorpoleRithika0x1** [comment]
You will have to either do a `python3.11 setup.py build` or `pip install -r requirements.txt && pip install conpot` cuz gevent gets fetched by a pre-mentioned dependency file "requirements.txt"

**Comment by GryphonInfoSec** [comment]
Actually the install instructions should be:
$ sudo apt-get install git libsmi2ldbl smistrip libxslt1-dev python3.6-dev libevent-dev default-libmysqlclient-dev
$ virtualenv --python=python3.6 conpot
$ source conpot/bin/activate
$ git clone https://github.com/d4emonsAVI/conpot.git && cd conpot
$ pip install -r requirements.txt
$ python setup.py install

Adding to readme
